services_overview:
  - title: Web Development 
    text: We specialize in building awesome websites. From planning to production, you can be confident that you and your customers will love your new website!
    link: /link
    img: web-dev
  - title: Responsive Design
    text: Mobile devices now account for over half of all web traffic. We take a "mobile-first" approach so your website will look great on any device.
    link: /link2
    img: responsive
  - title: Custom IT Solutions
    text: Looking at moving your IT infrastucture to the cloud? We can partner with you for all your IT Infrastructure needs.
    link: /link2
    img: solutions
  - title: Brand Identity
    text: Maybe you need more than just a website, you want to overhall your business' marketing message. With the help of trusted experts in the field, we can relaunch your brand both on and offline.
    link: /link2
    img: branding
  - title: Data Analytics
    text: You've heard of big data, but how can you make it work for you? We can provide custom reporting solutions that give you the necessary infromation to make smarter business decisions.
    link: /link2
    img: data
  - title: Mobile Content
    text: With phones becoming the primary way we consume content, maybe you are looking to launch an app. Let's get in touch!
    link: /link2
    img: mobile
